@startuml

!includeurl https://raw.githubusercontent.com/marcelofpfelix/plantuml-diagrams/master/skins/skin_clear.puml
skinparam backgroundcolor #FDFEFE

autonumber
box "Home" 
  participant User 
  participant "John Smith" as A #2D74BA
end box
actor B
database C

User -> A: DoWork 
activate A
== Initialization ==

A -> B: << createRequest >>
activate B
autonumber 15
B -> C: DoWork
activate C  #2D74BA
...5 minutes latter...
C --> B: WorkDone
destroy C
B --> A: RequestCreated
deactivate B
note right 
  This is **bold**
  This is //italics//
  This is ""monospaced""
  Thissss is --stroked--
  This is __underlined__
end note
A -> User: Done
deactivate A
@enduml
