@startuml

autonumber
hide footbox
box "Home" 
  participant User << (M,#27AE60) >> 
  participant "John Smith" as A #3498DB
end box
actor B
database C

User -> A: DoWork 
activate A
== Initialization ==

A -> B: << createRequest >>
activate B
autonumber 15
B -> C: DoWork
activate C  #E74C3C
...5 minutes latter...
C --> B: WorkDone
destroy C
B --> A: RequestCreated
deactivate B
note right 
  This is **bold**
  This is //italics//
  This is ""monospaced""
  Thissss is --stroked--
  This is __underlined__
end note
A -> User: Done
deactivate A

  footer //This is an example of a **sequence diagram**//


@enduml
