@startuml

!includeurl https://raw.githubusercontent.com/marcelofpfelix/plantuml-diagrams/master/skins/skin_clear.puml
skinparam backgroundcolor #FDFEFE

!includeurl https://raw.githubusercontent.com/marcelofpfelix/plantuml-diagrams/master/example/example1.puml

@enduml
