@startuml

skinparam DefaultFontColor #454645
skinparam backgroundcolor transparent
skinparam ParticipantPadding 5
skinparam BoxPadding 5
skinparam Padding 5
skinparam roundcorner 10
skinparam maxmessagesize 200
skinparam shadowing false
skinparam minClassWidth 70
skinparam ArrowColor #454645
skinparam ArrowThickness 2
skinparam ConditionEndStyle hline

skinparam activity {
FontColor #454645
BackgroundColor #EAECEE
BorderColor #ABB2B9
BarColor #ABB2B9
BorderThickness 2
DiamondBackgroundColor #EAECEE
DiamondBorderColor #ABB2B9
StartColor #ABB2B9
EndColor #ABB2B9
}


skinparam sequence {
FontColor #454645
ArrowColor #454645
ArrowThickness 2
DividerBorderColor #ABB2B9
DividerBackgroundColor #FFFFFF
ActorBorderColor #ABB2B9
ActorBackgroundColor #EAECEE
LifeLineBorderColor #ABB2B9
LifeLineBackgroundColor #EAECEE
ParticipantBorderColor #ABB2B9
ParticipantBackgroundColor #EAECEE
BoxBorderColor #ABB2B9
BoxBackgroundColor transparent
GroupBorderThickness 1
GroupBorderColor #ABB2B9
GroupBackgroundColor #EAECEE
}

skinparam note {
FontColor #454645
BorderColor #B7950B
BackgroundColor #FCF3CF
}

skinparam card {
FontColor #454645
BackgroundColor #EAECEE
BorderColor #ABB2B9
BorderThickness 2
ArrowColor #454645
FontColor #454645
}

skinparam storage {
FontColor #454645
BackgroundColor #EAECEE
BorderColor #ABB2B9
BorderThickness 2
}

skinparam component {
FontColor #454645
BackgroundColor #EAECEE
BorderColor #ABB2B9
BorderThickness 2
}

skinparam node {
FontColor #454645
BackgroundColor #EAECEE
BorderColor #ABB2B9
BorderThickness 2
}

skinparam database {
FontColor #454645
BackgroundColor #EAECEE
BorderColor #ABB2B9
BorderThickness 2
}

skinparam interface {
FontColor #454645
BackgroundColor #EAECEE
BorderColor #ABB2B9
BorderThickness 2
}

@enduml
