@startuml

!includeurl https://raw.githubusercontent.com/marcelofpfelix/plantuml-diagrams/master/skins/skin_clear.puml

skinparam backgroundcolor transparent
skinparam DefaultFontColor $midnightblue200
skinparam ArrowColor $midnightblue200

@enduml
