@startuml

skinparam DefaultFontColor #454645
skinparam backgroundcolor transparent
skinparam ParticipantPadding 5
skinparam BoxPadding 5
skinparam Padding 5
skinparam roundcorner 10
skinparam maxmessagesize 200
skinparam shadowing false
skinparam minClassWidth 70
skinparam ArrowColor #454645
skinparam ArrowThickness 2
skinparam ConditionEndStyle hline

skinparam activity {
FontColor #454645
BackgroundColor #EAECEE
BorderColor #ABB2B9
BarColor #ABB2B9
BorderThickness 2
DiamondBackgroundColor #EAECEE
DiamondBorderColor #ABB2B9
StartColor #ABB2B9
EndColor #ABB2B9
}


skinparam sequence {
FontColor #454645
ArrowColor #454645
ArrowThickness 2
DividerBorderColor #ABB2B9
DividerBackgroundColor #FFFFFF
DividerFontColor #454645
ActorBorderColor #ABB2B9
ActorBackgroundColor #EAECEE
LifeLineBorderColor #ABB2B9
LifeLineBackgroundColor #EAECEE
ParticipantBorderColor #ABB2B9
ParticipantBackgroundColor #EAECEE
ParticipantFontColor #454645
BoxBorderColor #ABB2B9
BoxBackgroundColor transparent
GroupBorderThickness 1
GroupBorderColor #ABB2B9
GroupBackgroundColor #EAECEE
}

skinparam note {
FontColor #454645
BorderColor #B7950B
BackgroundColor #FCF3CF
}

skinparam card {
FontColor #454645
BackgroundColor #EAECEE
BorderColor #ABB2B9
BorderThickness 2
ArrowColor #454645
FontColor #454645
}

skinparam storage {
FontColor #454645
BackgroundColor #EAECEE
BorderColor #ABB2B9
BorderThickness 2
}

skinparam component {
FontColor #454645
BackgroundColor #EAECEE
BorderColor #ABB2B9
BorderThickness 2
}

skinparam node {
FontColor #454645
BackgroundColor #EAECEE
BorderColor #ABB2B9
BorderThickness 2
}

skinparam database {
BackgroundColor #EAECEE
BorderColor #ABB2B9
BorderThickness 2
}

skinparam interface {
FontColor #454645
BackgroundColor #EAECEE
BorderColor #ABB2B9
BorderThickness 2
}

!$turquoise = "#1ABC9C"
!$greensea = "#16A085"
!$emerald = "#2ECC71"
!$nephritis = "#27AE60"
!$peterriver = "#3498DB"
!$belizehole = "#2980B9"
!$amethyst = "#9B59B6"
!$wisteria = "#8E44AD"
!$wetasphalt = "#34495E"
!$midnightblue = "#2C3E50"
!$sunflower = "#F1C40F"
!$orange = "#F39C12"
!$carrot = "#E67E22"
!$pumpkin = "#D35400"
!$alizarin = "#E74C3C"
!$pomegranate = "#C0392B"
!$clouds = "#ECF0F1"
!$silver = "#BDC3C7"
!$concrete = "#95A5A6"
!$asbestos = "#7F8C8D"

@enduml
