@startuml

!includeurl https://raw.githubusercontent.com/marcelofpfelix/plantuml-diagrams/master/skins/skin_clear.puml

skinparam backgroundcolor transparent
skinparam DefaultFontColor #ABB2B9
skinparam ArrowColor #ABB2B9

@enduml
