@startuml
skinparam ParticipantPadding 5
skinparam BoxPadding 5
skinparam Padding 5
skinparam sequenceArrowThickness 2
skinparam roundcorner 10
skinparam maxmessagesize 200
skinparam shadowing false
skinparam DefaultFontColor #454645
skinparam NoteBorderColor #B7950B
skinparam NoteBackgroundColor #FCF3CF
skinparam DatabaseBorderColor #ABB2B9
skinparam DatabaseBackgroundColor #EAECEE
skinparam minClassWidth 70

skinparam sequence {
ArrowColor #454645
ArrowThickness 2

DividerBorderColor #ABB2B9
DividerBackgroundColor #FFFFFF

ActorBorderColor #ABB2B9
ActorBackgroundColor #EAECEE

LifeLineBorderColor #ABB2B9
LifeLineBackgroundColor #EAECEE

ParticipantBorderColor #ABB2B9
ParticipantBackgroundColor #EAECEE

BoxBorderColor #ABB2B9
BoxBackgroundColor #FFFFFF
}

participant MSS
participant SBC
box "CSCF"
  participant "I-CSCF"
  participant "S-CSCF"
end box

MSS      [#red]->     "S-CSCF":  INVITE (O)
"S-CSCF" [#red]->     AS:        INVITE (O)
AS       [#blue]->    "S-CSCF":  INVITE (O)
"I-CSCF" [#blue]->    "S-CSCF":  INVITE (T)
"S-CSCF" [#blue]->    AS:        INVITE (T)
AS       [#green]->   "S-CSCF":  INVITE (T)
"S-CSCF" [#green]->    SBC:      INVITE (T)

@enduml
